    steps:
      # Clean and checkout
      - checkout: self
        clean: all
        continueOnError: 'false'

      # Build, test and generate artifact output
      - powershell: .\build.ps1 -Verbose
        displayName: 'Build, test and generate artifact output on working directory'
        continueOnError: 'false'
        env:
          CODECOV_TOKEN: $(CODECOV_TOKEN)
          COVERAGE_THRESHOLD: $(COVERAGE_THRESHOLD)
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          GITTER_ROOM_ID: $(GITTER_ROOM_ID)
          GITTER_TOKEN: $(GITTER_TOKEN)
          NUGET_API_KEY: $(NUGET_API_KEY)
          NUGET_API_URL: $(NUGET_API_URL)
